name: Playwright Tests with Allure

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Playwright tests (${{ matrix.tag }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [e2e, smoke]
    env:
      ALLURE_RESULTS: allure-results
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests with tag ${{ matrix.tag }}
        run: |
          npx playwright test --grep "@${{ matrix.tag }}"

      - name: Upload Allure results artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.tag }}
          path: allure-results

  allure-report:
    name: Generate & Publish Allure Report
    needs: test
    runs-on: ubuntu-latest
    env:
      ALLURE_RESULTS: allure-results
      ALLURE_HISTORY: allure-history
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Allure results for all tags
        uses: actions/download-artifact@v4
        with:
          path: downloaded-results

      - name: Merge Allure results
        run: |
          mkdir -p allure-results
          find downloaded-results -type d -name "allure-results-*" -exec cp -r {}/* allure-results/ \;

      - name: Checkout gh-pages branch for history
        run: |
          git fetch origin gh-pages:gh-pages || true
          git worktree add gh-pages gh-pages
        continue-on-error: true

      - name: Copy Allure history (if exists)
        run: |
          if [ -d "gh-pages/history" ]; then
            mkdir -p allure-results/history
            cp -r gh-pages/history/* allure-results/history/
          fi

      - name: Install Allure commandline
        run: npm install -g allure-commandline --save-dev

      - name: Generate Allure report
        run: |
          npx allure generate allure-results -o allure-report --clean

      - name: Copy history to report
        run: |
          mkdir -p allure-report/history
          if [ -d "allure-results/history" ]; then
            cp -r allure-results/history/* allure-report/history/
          fi

      - name: Deploy Allure report to gh-pages branch
        run: |
          cp -r allure-report/* gh-pages/
          git -C gh-pages add .
          git -C gh-pages config user.email "github-actions[bot]@users.noreply.github.com"
          git -C gh-pages config user.name "github-actions[bot]"
          git -C gh-pages commit -m "Update Allure report [skip ci]" || echo "No changes to commit"
          git -C gh-pages push origin gh-pages

      - name: Cleanup worktree
        if: always()
        run: |
          git worktree remove gh-pages --force
