name: Playwright Tests + Allure + Deploy

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [e2e, smoke]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run tests for tag ${{ matrix.tag }}
        run: npx playwright test --grep @${{ matrix.tag }}

      - name: Upload allure-results for ${{ matrix.tag }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.tag }}
          path: allure-results

  generate_and_deploy_report:
    needs: test_matrix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download all allure-results artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Merge allure results
        run: |
          mkdir combined_result
          cp -r artifacts/allure-results-e2e/* combined_result/
          cp -r artifacts/allure-results-smoke/* combined_result/

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate consolidated Allure report (single file)
        run: |
          allure generate --single-file combined_result --clean -o allure-report

      - name: Configure Git for push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy report to gh-pages branch
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          git clone --branch gh-pages --depth 1 https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }} gh-pages
          rm -rf gh-pages/*
          cp -r allure-report/* gh-pages/
          cd gh-pages
          git add .
          git commit -m "Update Allure report - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin gh-pages
