name: Playwright Tests and Allure Report

on:
  workflow_dispatch:

jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [e2e, smoke]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run ${{ matrix.tag }} tests
        run: npx playwright test --grep @${{ matrix.tag }}

      - name: Upload Allure results for ${{ matrix.tag }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.tag }}
          path: allure-results

  generate_and_publish_report:
    needs: test_matrix
    runs-on: ubuntu-latest
    steps:
      - name: Download all Allure result artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Merge Allure results
        run: |
          mkdir -p combined-results
          find artifacts -type d -name "allure-results-*" -exec cp -r {}/* combined-results/ \;

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure report (single file)
        run: |
          allure generate --single-file combined-results --clean -o allure-report

      - name: Push Allure report to gh-pages branch
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          REPO_URL="https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git"
          git clone --depth=1 "$REPO_URL" gh-pages-repo

          cd gh-pages-repo

          # Checkout gh-pages branch or create it if not exist
          git checkout gh-pages || git checkout -b gh-pages
          git pull origin gh-pages || echo "No existing remote branch"

          mkdir -p allure-report
          cp -r ../allure-report/* allure-report/

          git add .
          git commit -m "Update Allure report - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin gh-pages
