name: Playwright Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
   runs-on: ubuntu-latest
   env:
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@4

      - name: Setup Node
        uses: actions/setup-node@4
        with: 
          node-version: 18
      
      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        
      - name: Run all tests
        run: npx run test

      - name: Upload Allure Results  
        if: always()
        uses: actions/upload-artifact@4
        with:
          name: allure-results
          path: allure-results/
